---
title: "Parameterization of the meta-d' model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{parameterization}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dpi = 150, fig.width=8, fig.height=6, 
  fig.align='center', out.width = "75%"
)
```

This vignette describes the parameterization of the meta-d' model used in the `mRatio` package. For an in-depth review, we refer readers to Maniscalco & Lau (2012, 2014).


## Introduction
In metacognition research, decision-making is often categorized into two kinds. 

The *type 1* decision is the primary decision at hand, for example judging the orientation of a grating as left or right, or judging a word as either having been presented before (old) or not (new). In the context of the meta-d' model, the type 1 decision is a binary decision task (i.e., either a yes-no decision task or a two-alternative forced choice task).

In contrast, the *type 2* decision is the task of rating confidence in the type 1 decision. The meta-d' model is applicable where the type 2 decision is categorical (i.e., confidence is rated on an ordinal scale from `1` to `K`, where `1` indicates low confidence and `K` indicates high confidence).

In line with the distinction between type 1 and type 2 decisions, the meta-d' model is a conjunction of two models (one for each decision). Both models are based in Signal Detection Theory (SDT). However, the insight of the meta-d' model is that the information available for type 2 decisions might differ from the information available for type 1 decisions.



## Model for type 1 decisions
Under SDT, the observer is presented with a noisy signal depending on the underlying stimulus \eqn{x_1 \sim \mathcal{D}_S(d')} following a distribution \eqn{\mathcal{D}} dependent on a stimulus \eqn{S \in \{0, 1\}} and the observer's sensitivity \eqn{d'}. Typically, \eqn{\mathcal{D}} is chosen to be an equal-variance normal distribution, such that \deqn{\mathcal{D}_0(d') = \mathcal{N}(-\frac{d'}{2}, 1)} and \deqn{\mathcal{D}_1(d') = \mathcal{N}(\frac{d'}{2}, 1)}. However, this decision is not arbitrary and other options are available.

Given the noisy encoding \eqn{x_1}, the observer is tasked with determining the true value of \eqn{S}. To do so, they simply threshold \eqn{x_1} such that their response is \deqn{R = [x_1 > c]}. 


In this setup, the observer makes a correct response when \eqn{R = S}. More importantly, trials can be categorized into *hits* (\eqn{S = 1} and \eqn{R = 1}), *misses* (\eqn{S = 1} and \eqn{R = 0}), *false alarms* (FAs; \eqn{S = 0} and \eqn{R = 1}), and *correct rejections* (CRs; \eqn{S = 0} and \eqn{R = 0}). The generative model for type 1 decisions above implies the following response probabilities:

* Hit rate: \eqn{P(R=1 \;\vert\; S=1) = 1 - F_{\mathcal{D}}(c; \frac{d'}{2})}
* Miss rate: \eqn{P(R=0 \;\vert\; S=1) = F_{\mathcal{D}}(c; \frac{d'}{2})}
* FA rate: \eqn{P(R=1 \;\vert\; S=0) = 1 - F_{\mathcal{D}}(c; -\frac{d'}{2})}
* CR rate: \eqn{P(R=0 \;\vert\; S=0) = F_{\mathcal{D}}(c; -\frac{d'}{2})}

Since the hit rate and miss rate, as well as the FA rate and CR rate, are complements of one another, it is customary to model only the hit rate and FA rate. Then, where \eqn{N_\textrm{hit}}, \eqn{N_\textrm{miss}}, \eqn{N_\textrm{FA}}, and \eqn{N_\textrm{CR}} are the number of hits, misses, false alarms, and correct rejections, the model for type 1 decisions follows a Binomial likelihood \deqn{LL = \textrm{binomial_lpmf}(N_\textrm{hit} \;\vert\; N_\textrm{hit}+N_\textrm{miss}, 1 - F_{\mathcal{D}}(c; \frac{d'}{2})) + \textrm{binomial_lpmf}(N_\textrm{FA} \;\vert\; N_\textrm{FA}+N_\textrm{CR}, 1 - F_{\mathcal{D}}(c; -\frac{d'}{2}))}


## Model for type 2 decisions
In classical SDT, type 2 decisions are treated just like type 1 decisions but with more stringent or more liberal response criteria. However, this assumes that observers have access to the same information when making type 1 and type 2 decisions. In contrast, the meta-d' model assumes that type 2 decisions are derived from a separate decision variable \eqn{x_2 \sim \begin{cases}
\mathcal{D}_S^{(-\infty, \textrm{meta-}c]}(\textrm{meta-}d') & \textrm{if } R=0 \\
\mathcal{D}_S^{[\textrm{meta-}c, \infty)}(\textrm{meta-}d') & \textrm{if } R=1
\end{cases}}

Importantly, this decision variable follows the same distribution as for the type 1 decision, with two differences. First, the distribution is truncated either above or below at the type 1 criterion \eqn{\textrm{meta-}d'} depending on the initial type 1 response. This is so that the type 2 decision cannot contradict the type 1 decision (i.e., the meta-d' model does not allow for changes of mind). Second, the sensitivity for the type 2 decision is \exp{\textrm{meta-}d'} rather than \textrm{d'} to allow for task-level sensitivity and metacognitive sensitivity to differ.
